# Generated by Django 4.2.6 on 2023-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateField(auto_now_add=True)),
                ('tags', models.JSONField(verbose_name=models.BooleanField(default=False))),
                ('status', models.JSONField(verbose_name=models.CharField(max_length=200))),
            ],
        ),
    ]
