# Generated by Django 4.2.6 on 2023-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
        migrations.AddField(
            model_name='snippet',
            name='subgoals',
            field=models.ManyToManyField(blank=True, related_name='snippets', to='project.subgoal'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snippets', to='project.tag'),
        ),
    ]
