# Generated by Django 4.2.6 on 2023-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_subgoal_tag_alter_snippet_status_remove_snippet_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='status',
        ),
        migrations.AddField(
            model_name='snippet',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='subgoals',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Subgoal',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='snippet',
            name='subgoals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
