# Generated by Django 4.2.6 on 2023-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
    ]
