# Generated by Django 4.2.6 on 2023-10-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_tagss_remove_snippet_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tagss',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='status_1',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='status_2',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='status_3',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='status_4',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.snippet'),
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.snippet'),
        ),
    ]
