# Generated by Django 4.2.6 on 2023-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_subgoals_remove_snippet_subgoals_snippet_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
