# Generated by Django 4.2.6 on 2023-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_snippet_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='not_started',
            field=models.BooleanField(default=False),
        ),
    ]
