# Generated by Django 4.2.6 on 2023-10-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_snippet_not_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='completed',
            new_name='status1',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='not_started',
            new_name='status2',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='on_hold',
            new_name='status3',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='end',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='start',
        ),
        migrations.AddField(
            model_name='snippet',
            name='status4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='progress',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='subgoals',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='snippet',
            name='sub_goals',
            field=models.ManyToManyField(related_name='snippets', to='project.subgoal'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(related_name='snippets', to='project.tag'),
        ),
    ]
