# Generated by Django 4.2.6 on 2023-10-24 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_subgoal_tag_remove_tags_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subgoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgoals_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='status1',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='status2',
            new_name='not_started',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='status3',
            new_name='on_hold',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='status4',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='sub_goals',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
        migrations.AddField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='SubGoal',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.snippet'),
        ),
        migrations.AddField(
            model_name='subgoals',
            name='subgoals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.snippet'),
        ),
    ]
