# Generated by Django 4.2.6 on 2023-10-25 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_subgoals_tags_rename_status1_snippet_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='subgoalsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgoals_text_progress', models.CharField(max_length=200)),
                ('subgoalsProgress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.subgoals')),
            ],
        ),
    ]
