# Generated by Django 4.2.6 on 2023-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_snippet_created_subgoalsprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoals',
            name='subgoalsProgress',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='subgoalsProgress',
        ),
    ]
