# Generated by Django 4.2.6 on 2023-10-25 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_subgoals_subgoalsprogress_delete_subgoalsprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgoals',
            old_name='subgoalsProgress',
            new_name='isCompleted',
        ),
        migrations.AddField(
            model_name='snippet',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='snippet',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
