# Generated by Django 4.2.6 on 2023-10-27 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_rename_subgoalsprogress_subgoals_iscompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoals',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subgoals',
            name='subgoals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='project.snippet'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='project.snippet'),
        ),
    ]
