# Generated by Django 4.2.6 on 2023-11-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_subgoals_creation_date_alter_subgoals_subgoals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='end',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='start',
        ),
        migrations.RemoveField(
            model_name='subgoals',
            name='creation_date',
        ),
    ]
