# Generated by Django 4.2.6 on 2023-11-06 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_snippet_end_remove_snippet_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='snippet',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
